### ISSUE TITLE
Scintigraphie Parathyroide

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Scintigraphy#54]
Images de Test  : Repertoire Parathyroide => 2 images Antérieur
Elle sont réalisées avec 2 traceur differents (ou deux temps du meme traceur)
1 Traceur est une visualisation de la thyroide
1 Traceur est une visualiation de la Thryroide + de la parathyroide.

Le but est Ici de voir les parathyroide => On fait donc une soustraction des deux images.

2 cas de figure : 
Deux traceur different : I123 et un Tc99m pour le traceur (il ya des methode pour trouver le traceur dans les librairies). Trier I123 puis Tc99m
Meme traceur (Tc) alors trier par temps d'acquisition (de la plus ancienne à la plus recente)

Worflow : 
Fait un stack de deux images (les deux images antérieures)
Afficher Image 1, demander à l'utilsateur de déssiner une ROI Throide
Afficher Image 2 et demander et inserer la ROI Throide de l'étape précedente, demander à l'utilisateur de deplacer la ROI et valider
=> Normalisation, pendre la valeur du Max pour chaque ROI.
Calculer le ratio entre les deux
Multiplier tous les pixels de l'image de l'image la moins fixante par ce ratio (ImageJ command multiply) et sauver cette nouvelle image
Calculer la difference des deux images (calcul pixel par pixel) idem existe une commande ImageJ (me demander)

=> Fenetre resultat
Pas de calculs mais 2 Tab de Visualisation
=> 1 Tab capture des ROIs tel que dessinée
=> 1 Tab visualisation des deux images normalisées sur la Zone de la ROI et image de la soustraction avec le slider de contrast dynamique

**Comment by AngeleMts** [comment]
Je ne sais pas si c'est d'ici dont tu parlais mais du coup :
- Pour le premier point, je crois que je n'ai pas bien compris le concept de traceur, notamment dans le cas où il va falloir choisir entre deux méthodes
- Ensuite quelques questions sur les calculs et le workflow, mais je pense qu'il faut juste m'en parler pour que ça devienne plus clair
Il y aura le temps pour faire un vocal éventuellement? Après si c'est pas possible, par écrit ça me va aussi 👍

**Comment by salimkanoun** [comment]
Yes Demain on peut.

Dans cet examen il y a 2 techniques.
Le but est de voir les parathyroide qui sont 4 petites glandes en arriere de la thyroide (https://generalsurgery.ucsf.edu/media/10709229/anatomy-of-thyroid-gland_500x439.jpg)

- Double traceur: On utilise deux traceurs different, le 1er (Iode) ne se fixe que sur les cellules thyroidienne. Le second (Tc) se fixe sur la Thyroide et les parathyroide. On ijecte les deux produits en meme temps et on fait une acquisition. Comme les deux traceurs donnent des "signaux" differnets en une seule acquisition on est capable de produire deux images (Tc et Iode, les dexu signaux sont séparés dans deux images)
Donc en faisant la soustraction Tc - Iode il ne reste (en théorie) que la fixation des parathyroide. 

- Double Phase : Ici on utilise un seul traceur (Tc) mais on fait 2 acquisition à des temps différents. Cette technique utilise le "washout" le traceur disparait plus vite dans la thyroide que dans les parathyroide
Ici la soustraction des images est moins intéréssante, la comparaison est surtout visuelle mais elle peut aider les cas compliqués.

Pour ton programme il faut que tu detecte l'heure et le traceru des acquisition (on a des méthode pour ca)
Si tu a 2 images à la meme heure tu devrait en avoir une Tc et une Iode
Si tu a 2 images à deux temps differents tu devrait avoir 2 image en Tc, la plus ancienne est la pahse "early" et la seconde est la "late"
